//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSuite
    {
        public TestSuite()
        {
            this.TestPlans = new HashSet<TestPlan>();
        }
    
        public int TestSuiteID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<TestPlan> TestPlans { get; set; }
    }
}
