//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestRun
    {
        public int TestRunID { get; set; }
        public string Name { get; set; }
        public Nullable<int> TestPlanID { get; set; }
        public Nullable<System.DateTime> RunDate { get; set; }
        public string Description { get; set; }
        public string TestSteps { get; set; }
        public string ExpectedResults { get; set; }
        public string Status { get; set; }
    
        public virtual TestPlan TestPlan { get; set; }
    }
}
