//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPlan
    {
        public TestPlan()
        {
            this.TestRuns = new HashSet<TestRun>();
        }
    
        public int TestPlanID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> TestSuiteID { get; set; }
        public string FeaturesTested { get; set; }
        public string FeaturesNotTested { get; set; }
        public string Approach { get; set; }
        public string PassCriteria { get; set; }
        public string FailCriteria { get; set; }
        public string SuspensionCriteria { get; set; }
        public string ResumptionCriteria { get; set; }
        public string Deliverables { get; set; }
        public string Responsibilities { get; set; }
        public string Schedule { get; set; }
        public string Risks { get; set; }
    
        public virtual TestSuite TestSuite { get; set; }
        public virtual ICollection<TestRun> TestRuns { get; set; }
    }
}
